version: '3.8'

services:

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5555:5432"
    networks:
      - backend-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: quizdb,questiondb      
    volumes:
      - postgres-data:/var/lib/postgresql/data

  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - backend-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8765:8765"
    networks:
      - backend-network

  quiz-service:
    build:
      context: ./quiz-service
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      - backend-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quizdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000

  question-service:
    build:
      context: ./question-service
      dockerfile: Dockerfile
    ports:
      - "8050:8080"
    networks:
      - backend-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/questiondb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000

  prometheus:
    image: prom/prometheus:v2.30.0
    volumes:
      - ./container-monitor:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - '9090:9090'
    networks:
      - backend-network

  loki:
    image: grafana/loki:2.5.0
    ports:
      - '3100:3100'
    networks:
      - backend-network

  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - /var/log:/var/log
      - ./container-monitor:/etc/promtail
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - backend-network

  grafana:
    image: grafana/grafana:8.3.0
    ports:
      - '3000:3000'
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
