global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8765']

  - job_name: 'question'
    static_configs:
      - targets: ['question-service:8080']

  - job_name: 'quiz'
    static_configs:
      - targets: ['quiz-service:8090']

  - job_name: 'registry'
    static_configs:
      - targets: ['service-registry:8761']
